---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: git-creds
  annotations:
    tekton.dev/git-0: ${GIT_SERVER_URL}
spec:
  fromNamespace: tap-install
---
apiVersion: v1
kind: Secret
metadata:
  name: git-creds
  namespace: tap-install
  annotations:
    tekton.dev/git-0: ${GIT_SERVER_URL}
type: kubernetes.io/basic-auth
stringData:
  username: ${GIT_USERNAME}
  password: ${GIT_TOKEN}
#! Git domain CA certificate
#!  caFile: |
#!    -----BEGIN CERTIFICATE-----
#!    MIIFYDCCBEigAwIBAgIQQAF3ITfU6UK47naqPGQKtzANBgkqhkiG9w0BAQsFADA/
#!    MSQwIgYDVQQKExtEaWdpdG...
#!    -----END CERTIFICATE-----


